name: Main Branch CI

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run linting
        run: yarn lint

      - name: Check formatting
        run: yarn format

      - name: Run tests
        run: yarn test

      - name: Build project
        run: yarn build
